### ISSUE TITLE
Update images to latest version of Python

### ISSUE THREAD

**Issue by wilhen01** [aws-samples/aws-secrets-manager-rotation-lambdas#119]
It appears the latest version of the Key Rotation lambda applications (1.1.367) uses Python 3.9. Could new versions be published targeting Python 3.11 please?

**Comment by ckifer** [comment]
Just to pile onto this, I think there are still some on 3.7 as well. Mongo secret rotation for one

**Comment by jbct** [comment]
Hi wilhen01. Is there a particular reason you need these republished for targeting 3.11?

**Comment by wilhen01** [comment]
@jbct Python 3.9 is already EOL for active support; we're always keen to keep everything in our accounts running on fairly fresh runtime versions where possible. 

Python 3.9 still has security support so this isn't critical but from experience it generally pays dividends to ask for the updates before things hit Security EOL - I'm aware that things always need prioritising on roadmaps etc.

**Comment by jbct** [comment]
Thanks for the context, @wilhen01 . I assume this is speaking about upgrading the version of the modules deployed as part of our internal Lambda deployment, because we don't provide specific versions of libraries on GitHub.

We are currently investigating a better solution to keep these versions updated - I don't currently have an ETA, but this work is being prioritized.

**Comment by wilhen01** [comment]
Thanks @jbct - yeah it's the module versions deployed to the Serverless Application Repository accessible via AWS 👍
