### ISSUE TITLE
Postgres Multi User Rotation does not preserve grants

### ISSUE THREAD

**Issue by thekevinbrown** [aws-samples/aws-secrets-manager-rotation-lambdas#38]
From: https://forums.aws.amazon.com/thread.jspa?threadID=322708

1. We create an environment and apply a bunch of grants.
2. A rotation occurs. This copies the grants over to the new user that's created.
3. We continue to do dev work on the service, granting additional permissions on new tables.
4. Another rotation occurs. Since the other user already exists, the lambda doesn't try to copy grants over (e.g. it follows the logic in the else here: https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/blob/master/SecretsManagerRDSPostgreSQLRotationMultiUser/lambda_function.py#L194)
5. At this point, the grants applied as part of #3 aren't there, and we get permission denied errors.

**Comment by jweilhammer** [comment]
I believe this issue goes much deeper than just the grants from the users, I have noticed it breaking our services due to permission errors for schemas created by user2 and not being to be accessible for user1

Have opened this:
https://github.com/aws-samples/aws-secrets-manager-rotation-lambdas/issues/56

**Comment by goyalya** [comment]
We have addressed this issue with updating the [documentation](https://docs.aws.amazon.com/secretsmanager/latest/userguide/getting-started.html#rotating-secrets-one-user-one-password) on when to use single or Multi User rotation strategy.
